name: build-works
options:
  bundleIdPrefix: com.example
  developmentLanguage: en

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.buildworks
    PRODUCT_NAME: build-works
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    SUPPORTS_MACCATALYST: NO
    ALWAYS_SEARCH_USER_PATHS: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
    Release:
      ONLY_ACTIVE_ARCH: NO

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: 2.5.0

targets:
  build-works:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - path: build-works
    dependencies:
      - package: Supabase
        product: Supabase
    info:
      path: build-works/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  build-works:
    build:
      targets:
        build-works: all
    run:
      config: Debug
    archive:
      config: Release
